#   _____ _             _____                    __
#  /  ___| |           |_   _|                  / _|
#  \ `--.| | _____      _| |_ __ __ _ _ __  ___| |_ ___ _ __
#   `--. \ |/ _ \ \ /\ / / | '__/ _` | '_ \/ __|  _/ _ \ '__|
#  /\__/ / | (_) \ V  V /| | | | (_| | | | \__ \ ||  __/ |
#  \____/|_|\___/ \_/\_/ \_/_|  \__,_|_| |_|___/_| \___|_|
#
#
application-port: 8181
  # This port will be used to run the server
  # on and to contact other servers.
publish-collect-task-int: 5